# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flntr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flntr_app.Landlord'),
        ),
    ]
