# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flntr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='numberOfRooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flntr_app.Flat'),
        ),
    ]
